### ISSUE TITLE
question about the codes

### ISSUE THREAD

**Issue by zzzmm1** [kamwoh/sdc#1]
Thanks for your great work!
When will you release the training and testing codes ?

**Comment by kamwoh** [comment]
Hi, thanks for your attention. I am busy with another submission and will do it after the deadline. It should be released within the next week.

**Comment by zzzmm1** [comment]
Thanks for your excellent work!
I have some questions about the sdc loss:
It seems that quantization loss focus on improve the cosine similarity between v and v.sign and distance_preserving_loss focus on matching the cosine similarity distribution of v to the calibration distribution (beta_ppf).
Why not directly matching the cosine similarity distribution of v.sign (or v.tanh) to the calibration distribution?
Also the using hash_dist_ab and hash_dist_ba is confusing, cause cosine similarity is symmetry.

**Comment by zzzmm1** [comment]
Thanks for your excellent work!
I have some questions about the sdc loss:
It seems that quantization loss focus on improve the cosine similarity between v and v.sign and distance_preserving_loss focus on matching the cosine similarity distribution of v to the calibration distribution (beta_ppf).
Why not directly matching the cosine similarity distribution of v.sign (or v.tanh) to the calibration distribution?
Also the using hash_dist_ab and hash_dist_ba is confusing, cause cosine similarity is symmetry.

**Comment by kamwoh** [comment]
We use the identity activation because tanh/sign may suppress the gradient which may cause sub-optimal performance. Further, adding tanh/sign doesn't mean low quantization error, hence we have additional quantization loss.

For hash_dist_ab and hash_dist_ba, you are correct, I switched it back to a single hash_dist. Thanks for the suggestion.
